[2024-03-01 16:50:49,801] [ERROR] [auto_inspect.py:757] 'token'
[2024-03-01 16:50:49,802] [ERROR] [auto_inspect.py:758] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 740, in auto_inspect_platform_info
    if rows[token_name_list[-1]]:
KeyError: 'token'

[2024-03-01 16:51:19,724] [ERROR] [auto_inspect.py:757] 'token'
[2024-03-01 16:51:19,724] [ERROR] [auto_inspect.py:758] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 740, in auto_inspect_platform_info
    if rows[token_name_list[-1]]:
KeyError: 'token'

[2024-03-01 16:51:49,704] [ERROR] [auto_inspect.py:757] 'token'
[2024-03-01 16:51:49,705] [ERROR] [auto_inspect.py:758] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 740, in auto_inspect_platform_info
    if rows[token_name_list[-1]]:
KeyError: 'token'

[2024-03-01 16:52:19,731] [ERROR] [auto_inspect.py:757] 'token'
[2024-03-01 16:52:19,731] [ERROR] [auto_inspect.py:758] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 740, in auto_inspect_platform_info
    if rows[token_name_list[-1]]:
KeyError: 'token'

[2024-03-01 16:53:09,717] [ERROR] [auto_inspect.py:757] 'token'
[2024-03-01 16:53:09,718] [ERROR] [auto_inspect.py:758] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 740, in auto_inspect_platform_info
    if rows[token_name_list[-1]]:
KeyError: 'token'

[2024-03-01 16:53:59,702] [ERROR] [auto_inspect.py:757] 'token'
[2024-03-01 16:53:59,703] [ERROR] [auto_inspect.py:758] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 740, in auto_inspect_platform_info
    if rows[token_name_list[-1]]:
KeyError: 'token'

[2024-03-01 16:54:49,703] [ERROR] [auto_inspect.py:757] 'token'
[2024-03-01 16:54:49,704] [ERROR] [auto_inspect.py:758] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 740, in auto_inspect_platform_info
    if rows[token_name_list[-1]]:
KeyError: 'token'

[2024-03-01 16:55:39,705] [ERROR] [auto_inspect.py:757] 'token'
[2024-03-01 16:55:39,706] [ERROR] [auto_inspect.py:758] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 740, in auto_inspect_platform_info
    if rows[token_name_list[-1]]:
KeyError: 'token'

[2024-03-01 16:56:29,724] [ERROR] [auto_inspect.py:757] 'token'
[2024-03-01 16:56:29,724] [ERROR] [auto_inspect.py:758] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 740, in auto_inspect_platform_info
    if rows[token_name_list[-1]]:
KeyError: 'token'

[2024-03-01 16:57:19,712] [ERROR] [auto_inspect.py:757] 'token'
[2024-03-01 16:57:19,712] [ERROR] [auto_inspect.py:758] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 740, in auto_inspect_platform_info
    if rows[token_name_list[-1]]:
KeyError: 'token'

[2024-03-01 16:58:09,708] [ERROR] [auto_inspect.py:757] 'token'
[2024-03-01 16:58:09,709] [ERROR] [auto_inspect.py:758] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 740, in auto_inspect_platform_info
    if rows[token_name_list[-1]]:
KeyError: 'token'

[2024-04-07 12:14:09,563] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:14:09,565] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:14:49,714] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:14:49,714] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:15:29,487] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:15:29,488] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:16:19,691] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:16:19,694] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:17:00,952] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:17:00,954] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:17:39,721] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:17:39,722] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:18:19,718] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:18:19,718] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:18:59,696] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:18:59,697] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:19:39,701] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:19:39,701] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:20:19,706] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:20:19,706] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:20:59,698] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:20:59,698] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:21:39,794] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:21:39,794] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:22:19,770] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:22:19,770] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:22:59,830] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:22:59,831] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:23:39,696] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:23:39,697] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:24:19,687] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:24:19,688] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:24:59,688] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:24:59,689] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:25:39,701] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:25:39,702] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:26:19,781] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:26:19,781] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:26:59,704] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:26:59,704] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:27:39,805] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:27:39,806] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:28:19,786] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:28:19,786] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:28:59,775] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:28:59,775] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:29:39,733] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:29:39,733] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:30:19,691] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:30:19,692] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:30:59,711] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:30:59,712] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:31:39,722] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:31:39,722] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:32:19,749] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:32:19,750] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:32:59,792] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:32:59,792] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:33:39,706] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:33:39,707] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:34:19,696] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:34:19,696] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:34:59,725] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:34:59,726] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:35:39,687] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:35:39,688] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:36:19,705] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:36:19,705] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:36:59,900] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:36:59,901] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:37:39,790] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:37:39,790] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:38:19,743] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:38:19,743] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:38:59,815] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:38:59,816] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:39:39,801] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:39:39,801] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:40:19,724] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:40:19,725] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:40:59,685] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:40:59,685] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:41:39,722] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:41:39,722] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:42:19,678] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:42:19,679] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:42:59,695] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:42:59,696] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:43:39,740] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:43:39,740] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:44:19,700] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:44:19,701] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:44:59,744] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:44:59,744] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:45:39,715] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:45:39,716] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:46:19,711] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:46:19,711] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:46:59,709] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:46:59,710] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:47:39,738] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:47:39,739] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:48:19,684] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:48:19,685] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:48:59,809] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:48:59,810] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:49:39,700] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:49:39,701] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:50:19,694] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:50:19,695] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:50:59,726] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:50:59,727] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:51:39,737] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:51:39,738] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:52:19,779] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:52:19,780] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:52:59,689] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:52:59,690] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:53:39,763] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:53:39,763] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:54:19,713] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:54:19,713] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:54:59,751] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:54:59,752] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:55:39,738] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:55:39,738] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:56:19,752] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:56:19,752] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:56:59,774] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:56:59,775] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:57:39,771] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:57:39,771] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:58:20,502] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:58:20,502] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:58:59,716] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:58:59,716] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 12:59:39,709] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 12:59:39,710] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:00:19,802] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:00:19,802] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:00:59,700] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:00:59,701] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:01:39,674] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:01:39,674] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:02:19,788] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:02:19,788] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:02:59,693] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:02:59,694] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:03:39,813] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:03:39,814] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:04:20,059] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:04:20,059] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:04:59,691] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:04:59,691] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:05:39,797] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:05:39,797] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:06:20,180] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:06:20,180] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:06:59,721] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:06:59,722] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:07:39,676] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:07:39,677] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:08:19,739] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:08:19,739] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:08:59,725] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:08:59,726] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:09:39,801] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:09:39,801] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:10:19,813] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:10:19,813] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:10:59,814] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:10:59,815] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:11:39,805] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:11:39,806] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:12:19,848] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:12:19,849] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:12:59,776] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:12:59,777] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:13:39,680] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:13:39,680] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:14:19,709] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:14:19,710] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:14:59,811] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:14:59,811] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:15:39,667] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:15:39,668] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:16:19,686] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:16:19,686] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:16:59,730] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:16:59,730] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:17:39,724] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:17:39,724] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:18:19,668] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:18:19,669] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:18:59,775] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:18:59,776] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:19:39,711] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:19:39,711] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:20:19,691] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:20:19,691] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:20:59,709] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:20:59,710] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:21:39,790] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:21:39,790] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:22:19,794] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:22:19,794] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:22:59,810] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:22:59,810] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:23:39,724] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:23:39,724] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:24:19,820] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:24:19,820] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:24:59,882] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:24:59,883] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:25:39,792] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:25:39,793] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:26:19,690] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:26:19,691] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:27:00,418] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:27:00,418] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:27:39,771] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:27:39,772] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:28:19,737] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:28:19,738] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:28:59,990] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:28:59,991] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:29:39,718] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:29:39,718] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:30:19,737] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:30:19,738] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:30:59,733] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:30:59,733] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:31:39,742] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:31:39,742] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:32:19,815] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:32:19,816] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:32:59,830] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:32:59,831] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:33:39,712] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:33:39,713] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:34:19,739] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:34:19,739] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:34:59,793] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:34:59,793] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:35:39,690] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:35:39,690] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:36:19,700] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:36:19,701] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:36:59,753] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:36:59,754] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:37:39,794] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:37:39,795] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:38:19,797] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:38:19,798] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:38:59,701] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:38:59,701] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:39:39,784] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:39:39,785] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:40:19,720] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:40:19,720] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:40:59,787] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:40:59,787] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:41:39,712] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:41:39,713] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:42:19,716] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:42:19,717] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:42:59,693] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:42:59,695] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:43:39,713] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:43:39,714] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:44:19,777] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:44:19,777] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:44:59,777] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:44:59,778] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:45:39,720] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:45:39,721] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:46:19,706] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:46:19,707] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:46:59,731] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:46:59,732] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:47:41,706] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:47:41,708] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:48:19,697] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:48:19,698] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:48:59,773] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:48:59,773] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:49:39,707] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:49:39,707] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:50:19,778] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:50:19,778] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:50:59,748] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:50:59,749] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:51:52,935] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:51:52,936] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:52:32,833] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:52:32,833] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:53:12,986] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:53:12,986] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:53:52,863] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:53:52,863] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:54:32,829] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:54:32,829] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 993, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

[2024-04-07 13:56:00,058] [ERROR] [auto_inspect.py:793] 连接异常：请求超时！
[2024-04-07 13:56:00,059] [ERROR] [auto_inspect.py:794] Traceback (most recent call last):
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 787, in auto_inspect_platform_info
    res = send_request_with_retry("post",login_itf,headers,data=post_dict)
  File "D:\PycharmProjects\inspect_admin\index\crond\auto_inspect.py", line 994, in send_request_with_retry
    raise ConnectionError("连接异常：请求超时！")
ConnectionError: 连接异常：请求超时！

